# name: Rayzon
# on:
 # schedule:
    # * is a special character in YAML so you have to quote this string
  #  - cron:  '30 3,15 * * *'
 #jobs:
  #build:
   # runs-on: ubuntu-latest
    #steps:     
    #- name: OWASP ZAP Baseline Scan
     # uses: zaproxy/action-baseline@v0.6.1
      #with:
       # target: ""
